import { buildIterator } from '../iterator'

import { generator } from '../generator'

import schedule from '../data/calculableSchedule.json'

const expected = [
  { minute: 20,
    hour: 17,
    day: 1,
    date: 6,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 0,
    hour: 18,
    day: 1,
    date: 6,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 40,
    hour: 19,
    day: 1,
    date: 6,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 20,
    hour: 20,
    day: 1,
    date: 6,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 20,
    hour: 17,
    day: 3,
    date: 8,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 0,
    hour: 18,
    day: 3,
    date: 8,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 40,
    hour: 19,
    day: 3,
    date: 8,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 20,
    hour: 20,
    day: 3,
    date: 8,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лаб.',
    teacher: 'Майнина К.А.',
    room: '504/1' },
  { minute: 20,
    hour: 8,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 1,
    subject: 'Специальная лаборатория дипломного проектирования',
    type: 'пр.',
    teacher: 'Бабенко В.В.',
    room: '516/1' },
  { minute: 0,
    hour: 9,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 1,
    subject: 'Специальная лаборатория дипломного проектирования',
    type: 'пр.',
    teacher: 'Бабенко В.В.',
    room: '516/1' },
  { minute: 40,
    hour: 10,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 2,
    subject: 'Специальная лаборатория дипломного проектирования',
    type: 'пр.',
    teacher: 'Бабенко В.В.',
    room: '516/1' },
  { minute: 20,
    hour: 17,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '251/1' },
  { minute: 0,
    hour: 18,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '251/1' },
  { minute: 40,
    hour: 19,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '251/1' },
  { minute: 20,
    hour: 20,
    day: 5,
    date: 10,
    month: 4,
    year: 2019,
    call: 7,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '251/1' },
  { minute: 40,
    hour: 10,
    day: 6,
    date: 11,
    month: 4,
    year: 2019,
    call: 2,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '412/1' },
  { minute: 20,
    hour: 17,
    day: 6,
    date: 11,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '412/1' },
  { minute: 0,
    hour: 18,
    day: 6,
    date: 11,
    month: 4,
    year: 2019,
    call: 6,
    subject: 'Программная инженерия и информационный менеджмент',
    type: 'лек.',
    teacher: 'Майнина К.А.',
    room: '412/1' }
]

test('Generate schedule', () => {
  const { period: { start, end }, rules } = schedule
  const iterator = buildIterator(new Date(start), new Date(end), {
    minute: {
      step: 100
    }
  })
  const gen = generator(rules, iterator)
  const items = [...gen].filter(data => data.subject)
  expect(items).toEqual(expected)
})